# Generated by Django 2.1.4 on 2018-12-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20181204_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='texte',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='project',
            name='background',
            field=models.ImageField(upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
