# Generated by Django 2.1.4 on 2018-12-04 15:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20181204_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='text',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
