# Generated by Django 2.1.4 on 2018-12-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20181204_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='presentation_text',
            field=models.TextField(null=True),
        ),
    ]
