# Generated by Django 2.1.4 on 2018-12-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_presentation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='view_order',
            field=models.IntegerField(choices=[('top_left', 1), ('top_right', 2), ('bottom_left', 3), ('bottom_right', 4)], null=True),
        ),
    ]
