# Generated by Django 2.1.4 on 2018-12-04 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20181204_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_upload',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
